spring:
  application:
    name: chat-pr
  profiles:
    active: dev
logging:
  file:
    name: chat-pr.log

---
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/chat-dev
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
  data:
    redis:
      repositories:
        enabled: true
    cassandra:
      contact-points: 127.0.0.1
      username: <username, if any>
      password: <password, if any>
      keyspace: chat-keyspace
      port: 9042
      schema-action: NONE



server:
  port: 8080

logging.level.org.springframework.web: DEBUG

---
spring:
  profiles: prod